### ISSUE TITLE
Diskussion: Backend / Frontend und Tischverantwortlicher?

### ISSUE THREAD

**Issue by FinstererFred** [FinstererFred/Schafkopf#1]
Ich wäre dafür ein Backend (admin/bootstrap) für die Stammdatenverwaltung zu machen, und ein Frontend für die Dateneingabe für die Spiele? 

Müssen wir einen Tischverantwortlichen pflegen, oder darf jeder Spieler für alle Tische 
in denen er ist, Daten erfassen?

**Comment by Schwaeg** [comment]
Jo Backend für die Pflege der Stammdaten resultierend aus der Datenbankstruktur und Dateneingabe nur für den "Tischersteller".

**Comment by FinstererFred** [comment]
dateneingabe kann nun von jedem vorgenommen werden
