### ISSUE TITLE
Frontend erstellen

### ISSUE THREAD

**Issue by FinstererFred** [FinstererFred/Schafkopf#4]
Frontend mit eingabe für Tischverantwortlichen erstellen

**Comment by forskris** [comment]
Ich hab mal ein Mockup zur groben Anordnung der Elemente gemacht.
Oben können die Tische ausgewählt werden, darunter dann Eingabe für die einzelnen Spiele und Tabellen-Übersicht der Spiele mit Kontostand

**Comment by FinstererFred** [comment]
sieht gut aus, so machen wirs

**Comment by FinstererFred** [comment]
dann fang ich mal an damit, willst du dann das backend machen?

**Comment by FinstererFred** [comment]
frontend inital jetzt funktionsfähig

todo frontend:
- login für benutzer
- offset in datenbank auslagern
- usability auf mobilgerät testen
- hypsch machen
